#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4G

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=false
org.gradle.parallel=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#Compose Desktop hot reload (hotRunDesktop)
mainClass=uk.tsundokus.composeapp.MainKt

APP_VERSION=0.1.0
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
