package uk.tsundokus.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// ---- Light (from Tsundoku design tokens) ----
val md_theme_light_primary = Color(0xFF9A4A00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDCBE)
val md_theme_light_onPrimaryContainer = Color(0xFF311300)
val md_theme_light_secondary = Color(0xFF765848)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCC5)
val md_theme_light_onSecondaryContainer = Color(0xFF2B1709)
val md_theme_light_tertiary = Color(0xFF006B5F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF8FF2E1)
val md_theme_light_onTertiaryContainer = Color(0xFF00201C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFF8F4)
val md_theme_light_onBackground = Color(0xFF221A13)
val md_theme_light_surface = Color(0xFFFFF8F4)
val md_theme_light_onSurface = Color(0xFF221A13)
val md_theme_light_surfaceVariant = Color(0xFFF4DED0)
val md_theme_light_onSurfaceVariant = Color(0xFF52443A)
val md_theme_light_surfaceDim = Color(0xFFE5D8CC)
val md_theme_light_surfaceBright = Color(0xFFFFF8F4)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFFFF1E7)
val md_theme_light_surfaceContainer = Color(0xFFFBEBDF)
val md_theme_light_surfaceContainerHigh = Color(0xFFF5E5D9)
val md_theme_light_surfaceContainerHighest = Color(0xFFEFDFD3)
val md_theme_light_outline = Color(0xFF847468)
val md_theme_light_outlineVariant = Color(0xFFD7C3B4)
val md_theme_light_inverseSurface = Color(0xFF382E26)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE0)
val md_theme_light_inversePrimary = Color(0xFFFFB77A)
val md_theme_light_surfaceTint = Color(0xFF9A4A00)
val md_theme_light_scrim = Color(0xFF000000)

// ---- Dark ----
val md_theme_dark_primary = Color(0xFFFFB77A)
val md_theme_dark_onPrimary = Color(0xFF522300)
val md_theme_dark_primaryContainer = Color(0xFF7A3900)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCBE)
val md_theme_dark_secondary = Color(0xFFE6BC9D)
val md_theme_dark_onSecondary = Color(0xFF432B1B)
val md_theme_dark_secondaryContainer = Color(0xFF5C4132)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCC5)
val md_theme_dark_tertiary = Color(0xFF6FD5C4)
val md_theme_dark_onTertiary = Color(0xFF003730)
val md_theme_dark_tertiaryContainer = Color(0xFF004F46)
val md_theme_dark_onTertiaryContainer = Color(0xFF8FF2E1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF19120C)
val md_theme_dark_onBackground = Color(0xFFEEE0D2)
val md_theme_dark_surface = Color(0xFF19120C)
val md_theme_dark_onSurface = Color(0xFFEEE0D2)
val md_theme_dark_surfaceVariant = Color(0xFF52443A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C3B4)
val md_theme_dark_surfaceDim = Color(0xFF19120C)
val md_theme_dark_surfaceBright = Color(0xFF403830)
val md_theme_dark_surfaceContainerLowest = Color(0xFF130C07)
val md_theme_dark_surfaceContainerLow = Color(0xFF221A13)
val md_theme_dark_surfaceContainer = Color(0xFF261E17)
val md_theme_dark_surfaceContainerHigh = Color(0xFF312921)
val md_theme_dark_surfaceContainerHighest = Color(0xFF3D342B)
val md_theme_dark_outline = Color(0xFF9F8D7F)
val md_theme_dark_outlineVariant = Color(0xFF52443A)
val md_theme_dark_inverseSurface = Color(0xFFEEE0D2)
val md_theme_dark_inverseOnSurface = Color(0xFF382E26)
val md_theme_dark_inversePrimary = Color(0xFF9A4A00)
val md_theme_dark_surfaceTint = Color(0xFFFFB77A)
val md_theme_dark_scrim = Color(0xFF000000)

// ---- Brand accents (logo tile / decorative) ----
val brand_cream = Color(0xFFFBE9C7)
val brand_orange = Color(0xFFD2762A)
val brand_deep = Color(0xFF612000)

// ---- Extended semantic colors (success / danger / muted + primary text) ----
val extended_light_positive = Color(0xFF006B5F)
val extended_light_positiveContainer = Color(0xFF8FF2E1)
val extended_light_onPositiveContainer = Color(0xFF00201C)
val extended_light_negative = Color(0xFFBA1A1A)
val extended_light_negativeContainer = Color(0xFFFFDAD6)
val extended_light_onNegativeContainer = Color(0xFF410002)
val extended_light_settled = Color(0xFF847468)
val extended_light_settledContainer = Color(0xFFF5E5D9)
val extended_light_onSettledContainer = Color(0xFF52443A)
val extended_light_deleted = Color(0xFF847468)
val extended_light_deletedContainer = Color(0xFFF5E5D9)
val extended_light_textPrimary = Color(0xFF221A13)

val extended_dark_positive = Color(0xFF6FD5C4)
val extended_dark_positiveContainer = Color(0xFF004F46)
val extended_dark_onPositiveContainer = Color(0xFF8FF2E1)
val extended_dark_negative = Color(0xFFFFB4AB)
val extended_dark_negativeContainer = Color(0xFF93000A)
val extended_dark_onNegativeContainer = Color(0xFFFFDAD6)
val extended_dark_settled = Color(0xFF9F8D7F)
val extended_dark_settledContainer = Color(0xFF312921)
val extended_dark_onSettledContainer = Color(0xFFD7C3B4)
val extended_dark_deleted = Color(0xFF9F8D7F)
val extended_dark_deletedContainer = Color(0xFF312921)
val extended_dark_textPrimary = Color(0xFFEEE0D2)
